name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        job: [lint, test, type-check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn install --pure-lock
        
      - name: ${{ matrix.job }}
        run: npm run ${{ matrix.job }}
